name: inventory_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  dio: ^4.0.4
  shared_preferences: ^2.0.10

dev_dependencies: 
  flutter_test: 
    sdk: flutter


flutter: 
  uses-material-design: true

